### ISSUE TITLE
Create a Public Dashboard for the CO2 Data

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-sensor#6]
I would really like to create a public dashboard that displays the CO2 measurements and the associated data on a map.

My inspiration is the [Purple Air Map](http://purpleair.com/) map. They do a good job presenting the data in a nice interface:

![image](https://user-images.githubusercontent.com/2559382/123307337-3b20e200-d4d7-11eb-826f-9cd1193991c2.png)

According to the [PurpleAir page](PurpleAir uses HighCharts and data stored on ThingSpeak to create graphs on the PurpleAir map.): "PurpleAir uses [HighCharts ](https://www.highcharts.com/) and data stored on [ThingSpeak](https://thingspeak.com/) to create graphs on the PurpleAir map."

**Data Storage** The current data is logged by each sensor node to the [InfluxDB Cloud](https://www.influxdata.com/products/influxdb-cloud/). InfluxDB seems like a great backend solution for the time series, so sticking with that as the database would seem to make sense.

**Visualization Solutions Explored**
- [Grafana World Map Plugin](https://grafana.com/grafana/plugins/grafana-worldmap-panel/) - Grafana can easily connect to InfluxDB and seems to have a map view. Grafana is open source, but the deployment of a public-facing dashboard is a bit tricky.
- [Highcharts](https://www.highcharts.com/products/maps/) - This is the solution used by PurpleAir. It seems nice, but is expensive :(
- [Dash](https://plotly.com/dash/) - Another solution proposed by @lalligagger. This is nice because it's open-source and seems to meet all the requirements :). Deployment is easy via Heroku or the Dash enterprise service to start out with

**Proposed Solution**
- Going to go with Dash for now :)

**Comment by lalligagger** [comment]
I'm always looking for cool Dash projects :)

**Comment by keenanjohnson** [comment]
@lalligagger! Awesome! Want to take a stab at mocking up what a Dash dashboard might be like for the sensors?

**Comment by lalligagger** [comment]
I'm in. Can you drop some data in the format you're expecting? Influx DB stash is good. I looked at the public network you mentioned but their data doesn't look to be fully live yet.

**Comment by keenanjohnson** [comment]
Sure thing! Here is a dump of some of the data I have in my influx DB testing database so far: 
[2021-06-13-22-45_influxdb_data.csv](https://github.com/keenanjohnson/ghg-gas-cloud/files/6645867/2021-06-13-22-45_influxdb_data.csv)

**Comment by keenanjohnson** [comment]
In #9 I decided to stick with InfluxDB + Dash for the database side. 

Now that that is decided and the GPS data is being logged to the database per #10, it should be possible to create a map visualization of where each sensor is and what the current readings are at that location.

**Comment by keenanjohnson** [comment]
Something like this:

https://user-images.githubusercontent.com/2559382/122119420-037eaf80-cdde-11eb-8ed7-de7aa96c0001.png

**Comment by keenanjohnson** [comment]
![image](https://user-images.githubusercontent.com/2559382/123214389-00d62700-d47c-11eb-9102-38e566cc7131.png)

**Comment by lalligagger** [comment]
Cool, this is definitely possible! I have been slammed with another project and paper due, but I can help out at some point in the next couple of months.

Are you planning on an AWS account attached to the project? For public deployment of the dashboard, I'd be looking at Elastic Beanstalk based on experience. Heroku is another (free) option but I'm not familiar with that deployment.

**Comment by keenanjohnson** [comment]
No worries @lalligagger :). This project isn't in a rush, I'm just excited about it.

Right now my goal is to keep costs down in the short term, so I'll probably start with Heroku in the short term since it is free. Seems like it won't be a big deal to transfer the hosting if AWS seems like a better long term solution.

**Comment by keenanjohnson** [comment]
@JohannesBrand any thoughts on this?

**Comment by keenanjohnson** [comment]
I prototyped a quick Dash dashboard hosted on Heroku in another repo [here.](https://github.com/keenanjohnson/ghg-cloud-dash)

That site is deployed to Heroku and is [viewable live at this link for now.](https://ghg-cloud.herokuapp.com/)

Just a pretty simple graph of my one sensor for now. Next will be to add a map view that can display multiple sensors. 

![image](https://user-images.githubusercontent.com/2559382/123486760-83b4ca00-d5c1-11eb-8cf2-4978dedf999f.png)

**Comment by JohannesBrand** [comment]
> @JohannesBrand any thoughts on this?

I've used grafana and I think it's really easy to use: even a public facing dashboard was just minutes as long as you had access to a registered domain. I've looked at dash before, but never really used it. But I've seen you've been able to pull a dashboard off with dash in no time -> so it looks like a very good solution to me. great!  

one downside that I found about grafana was: it was not as customizable as I thought, so maybe another plus point for dash? However, the out-of-the-box query builder and visualizations were just great. I think that's where grafana might offer a little bit more.

**Comment by lalligagger** [comment]
Wow, awesome start! This is exactly what I would have been able to tee up for you quickly, minus a Heroku deploy!
My initial suggestions on filtering would be one or more of:
- A date range selector on the timeseries plot. This could generate mean on the map and other stats in a table.
- A separate date range picker + drop-down to filters on sites, data types as well.
- Drop in a DataTable with filters turned on, for regex style filtering across columns (that can be linked to plot callback).

I could still help build in callbacks or other features as desired.

**Comment by keenanjohnson** [comment]
Yeah I'd love any help as I'm still very much a dash noob haha. Those are all great suggestions though!

**Comment by lalligagger** [comment]
Here is little a multi-page app w/ map I started working on a few weeks ago and then stalled on. There is also single-page version that doesn't include a map.  https://github.com/lalligagger/mtbtlm

I like the 3d global style you're using, especially for the CO2 use case! Basically, if you can narrow in on any specific features/ cross-filtering you'd like to enable, I could jump in to assist with that in mind.

**Comment by keenanjohnson** [comment]
Calling this dashboard done for now and I'll create issues for more specific changes as we go.
